2020-05-02 00:00:05.618  INFO 16056 --- [http-nio-8100-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-05-02 00:00:05.626  INFO 16056 --- [http-nio-8100-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-05-02 00:00:05.637  INFO 16056 --- [http-nio-8100-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 11 ms
2020-05-02 00:00:10.481  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:00:11.506  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:00:11.507  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:00:41.545  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:00:42.568  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:00:42.569  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:00:44.203  WARN 16056 --- [http-nio-8100-exec-4] o.s.web.servlet.PageNotFound             : Request method 'GET' not supported
2020-05-02 00:00:44.206  WARN 16056 --- [http-nio-8100-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'GET' not supported]
2020-05-02 00:01:12.589  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:01:13.603  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:01:13.603  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:01:43.619  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:01:44.625  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:01:44.627  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:02:14.657  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:02:15.689  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:02:15.689  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:02:43.836  INFO 16056 --- [Thread-48] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application USER-SERVICE with eureka with status DOWN
2020-05-02 00:02:43.838  WARN 16056 --- [Thread-48] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1588357963838, current=DOWN, previous=UP]
2020-05-02 00:02:43.848  INFO 16056 --- [Thread-48] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-05-02 00:02:43.851  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:02:43.866  INFO 16056 --- [Thread-48] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2020-05-02 00:02:43.920  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - Re-registering apps/USER-SERVICE
2020-05-02 00:02:43.921  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100: registering service...
2020-05-02 00:02:43.930  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - registration status: 204
2020-05-02 00:02:44.869  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:02:44.869  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:02:44.896  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] o.s.c.h.RefreshScopeHealthIndicator      : Health check failed

org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'refreshScope': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:208) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1290) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:1925) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.cloud.health.RefreshScopeHealthIndicator.doHealthCheck(RefreshScopeHealthIndicator.java:49) ~[spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) ~[spring-boot-actuator-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_171]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_171]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_171]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_171]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:195) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:176) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:170) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1419) ~[eureka-client-1.9.17.jar:1.9.17]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117) ~[eureka-client-1.9.17.jar:1.9.17]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) ~[eureka-client-1.9.17.jar:1.9.17]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]

2020-05-02 00:02:44.910  INFO 16056 --- [Thread-48] com.netflix.discovery.DiscoveryClient    : Unregistering ...
2020-05-02 00:02:44.916  INFO 16056 --- [Thread-48] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - deregister  status: 200
2020-05-02 00:02:44.931  INFO 16056 --- [Thread-48] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
2020-05-02 00:02:46.196  INFO 16056 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:02:47.201  INFO 16056 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:02:47.202  WARN 16056 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:02:47.204  INFO 16056 --- [restartedMain] c.m.user.app.UserServiceApplication      : No active profile set, falling back to default profiles: default
2020-05-02 00:02:48.043  INFO 16056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-05-02 00:02:48.043  INFO 16056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2020-05-02 00:02:48.062  INFO 16056 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 18ms. Found 1 Redis repository interfaces.
2020-05-02 00:02:48.205  INFO 16056 --- [restartedMain] o.s.cloud.context.scope.GenericScope     : BeanFactory id=62290dc6-6f8a-3087-8ea1-757c4ba46ebd
2020-05-02 00:02:48.484  INFO 16056 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8100 (http)
2020-05-02 00:02:48.484  INFO 16056 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-05-02 00:02:48.485  INFO 16056 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.33]
2020-05-02 00:02:48.530  INFO 16056 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-05-02 00:02:48.531  INFO 16056 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1316 ms
2020-05-02 00:02:49.217  INFO 16056 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2020-05-02 00:02:49.344  INFO 16056 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/actuator'
2020-05-02 00:02:49.380  INFO 16056 --- [restartedMain] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2020-05-02 00:02:49.388  WARN 16056 --- [restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2020-05-02 00:02:49.388  INFO 16056 --- [restartedMain] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2020-05-02 00:02:49.442  INFO 16056 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-05-02 00:02:49.874  WARN 16056 --- [restartedMain] ockingLoadBalancerClientRibbonWarnLogger : You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
2020-05-02 00:02:49.907  INFO 16056 --- [restartedMain] o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
2020-05-02 00:02:49.910  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
2020-05-02 00:02:49.911  INFO 16056 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2020-05-02 00:02:49.912  INFO 16056 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2020-05-02 00:02:49.912  INFO 16056 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2020-05-02 00:02:49.912  INFO 16056 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2020-05-02 00:02:49.970  INFO 16056 --- [restartedMain] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-05-02 00:02:49.970  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2020-05-02 00:02:49.970  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2020-05-02 00:02:49.970  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2020-05-02 00:02:49.971  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Application is null : false
2020-05-02 00:02:49.971  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2020-05-02 00:02:49.971  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2020-05-02 00:02:49.971  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2020-05-02 00:02:49.975  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : The response status is 200
2020-05-02 00:02:49.976  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Starting heartbeat executor: renew interval is: 1
2020-05-02 00:02:49.976  INFO 16056 --- [restartedMain] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 4
2020-05-02 00:02:49.977  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1588357969977 with initial instances count: 1
2020-05-02 00:02:49.978  INFO 16056 --- [restartedMain] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application USER-SERVICE with eureka with status UP
2020-05-02 00:02:49.978  INFO 16056 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1588357969978, current=UP, previous=STARTING]
2020-05-02 00:02:49.978  WARN 16056 --- [restartedMain] c.n.discovery.InstanceInfoReplicator     : Ignoring onDemand update due to rate limiter
2020-05-02 00:02:49.979  INFO 16056 --- [restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2020-05-02 00:02:49.980  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:02:49.981  INFO 16056 --- [restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2020-05-02 00:02:49.985  INFO 16056 --- [restartedMain] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2020-05-02 00:02:50.019  INFO 16056 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8100 (http) with context path ''
2020-05-02 00:02:50.019  INFO 16056 --- [restartedMain] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 8100
2020-05-02 00:02:50.377  INFO 16056 --- [restartedMain] c.m.user.app.UserServiceApplication      : Started UserServiceApplication in 4.911 seconds (JVM running for 473.661)
2020-05-02 00:02:50.380  INFO 16056 --- [restartedMain] .ConditionEvaluationDeltaLoggingListener : Condition evaluation unchanged
2020-05-02 00:02:50.981  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - Re-registering apps/USER-SERVICE
2020-05-02 00:02:50.981  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100: registering service...
2020-05-02 00:02:50.984  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:02:50.984  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:02:50.987  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - registration status: 204
2020-05-02 00:02:50.993  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:02:51.998  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:02:51.999  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:03:05.242  INFO 16056 --- [http-nio-8100-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-05-02 00:03:05.243  INFO 16056 --- [http-nio-8100-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-05-02 00:03:05.249  INFO 16056 --- [http-nio-8100-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 6 ms
2020-05-02 00:03:22.024  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:03:23.044  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:03:23.045  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:03:53.075  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:03:54.093  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:03:54.094  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:04:11.062  WARN 16056 --- [http-nio-8100-exec-7] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.data.mapping.MappingException: No property user found on entity class com.microservices.user.app.entity.ShippingAddress to bind constructor parameter to!]
2020-05-02 00:04:24.119  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:04:25.246  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:04:25.247  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:04:54.968  WARN 16056 --- [http-nio-8100-exec-8] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.data.mapping.MappingException: No property user found on entity class com.microservices.user.app.entity.ShippingAddress to bind constructor parameter to!]
2020-05-02 00:04:55.276  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:04:56.287  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:04:56.287  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:04:56.923  WARN 16056 --- [http-nio-8100-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.data.mapping.MappingException: No property user found on entity class com.microservices.user.app.entity.ShippingAddress to bind constructor parameter to!]
2020-05-02 00:05:03.171  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] inMXBeanRegistrar$SpringApplicationAdmin : Application shutdown requested.
2020-05-02 00:05:03.172  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application USER-SERVICE with eureka with status DOWN
2020-05-02 00:05:03.172  WARN 16056 --- [RMI TCP Connection(29)-127.0.0.1] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1588358103172, current=DOWN, previous=UP]
2020-05-02 00:05:03.176  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-05-02 00:05:03.177  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:05:03.183  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2020-05-02 00:05:04.048  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - Re-registering apps/USER-SERVICE
2020-05-02 00:05:04.049  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100: registering service...
2020-05-02 00:05:04.068  INFO 16056 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - registration status: 204
2020-05-02 00:05:04.186  INFO 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:05:04.187  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:05:04.213  WARN 16056 --- [DiscoveryClient-InstanceInfoReplicator-0] o.s.c.h.RefreshScopeHealthIndicator      : Health check failed

org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'refreshScope': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:208) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1290) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:1925) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.cloud.health.RefreshScopeHealthIndicator.doHealthCheck(RefreshScopeHealthIndicator.java:49) ~[spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) ~[spring-boot-actuator-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_171]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_171]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_171]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_171]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:195) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:176) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:170) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1419) ~[eureka-client-1.9.17.jar:1.9.17]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117) ~[eureka-client-1.9.17.jar:1.9.17]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) ~[eureka-client-1.9.17.jar:1.9.17]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]

2020-05-02 00:05:04.227  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] com.netflix.discovery.DiscoveryClient    : Unregistering ...
2020-05-02 00:05:04.237  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - deregister  status: 200
2020-05-02 00:05:04.260  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
2020-05-02 00:05:04.458  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-05-02 00:05:04.460  INFO 16056 --- [RMI TCP Connection(29)-127.0.0.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Destroying Spring FrameworkServlet 'dispatcherServlet'
2020-05-02 00:05:20.320  INFO 16528 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:05:21.432  INFO 16528 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:05:21.435  WARN 16528 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:05:21.443  INFO 16528 --- [restartedMain] c.m.user.app.UserServiceApplication      : No active profile set, falling back to default profiles: default
2020-05-02 00:05:22.752  INFO 16528 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-05-02 00:05:22.755  INFO 16528 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2020-05-02 00:05:22.841  INFO 16528 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 71ms. Found 1 Redis repository interfaces.
2020-05-02 00:05:22.988  WARN 16528 --- [restartedMain] o.s.boot.actuate.endpoint.EndpointId     : Endpoint ID 'service-registry' contains invalid characters, please migrate to a valid format.
2020-05-02 00:05:23.178  INFO 16528 --- [restartedMain] o.s.cloud.context.scope.GenericScope     : BeanFactory id=62290dc6-6f8a-3087-8ea1-757c4ba46ebd
2020-05-02 00:05:23.988  INFO 16528 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8100 (http)
2020-05-02 00:05:24.000  INFO 16528 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-05-02 00:05:24.001  INFO 16528 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.33]
2020-05-02 00:05:24.178  INFO 16528 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-05-02 00:05:24.179  INFO 16528 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2675 ms
2020-05-02 00:05:24.297  WARN 16528 --- [restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2020-05-02 00:05:24.298  INFO 16528 --- [restartedMain] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2020-05-02 00:05:24.311  INFO 16528 --- [restartedMain] c.netflix.config.DynamicPropertyFactory  : DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@32c83926
2020-05-02 00:05:25.544  INFO 16528 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2020-05-02 00:05:25.908  INFO 16528 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/actuator'
2020-05-02 00:05:25.980  INFO 16528 --- [restartedMain] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2020-05-02 00:05:26.001  WARN 16528 --- [restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2020-05-02 00:05:26.001  INFO 16528 --- [restartedMain] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2020-05-02 00:05:26.139  INFO 16528 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-05-02 00:05:26.807  WARN 16528 --- [restartedMain] ockingLoadBalancerClientRibbonWarnLogger : You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
2020-05-02 00:05:26.927  INFO 16528 --- [restartedMain] o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
2020-05-02 00:05:26.995  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
2020-05-02 00:05:27.348  INFO 16528 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2020-05-02 00:05:27.349  INFO 16528 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2020-05-02 00:05:27.457  INFO 16528 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2020-05-02 00:05:27.457  INFO 16528 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2020-05-02 00:05:27.644  INFO 16528 --- [restartedMain] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-05-02 00:05:27.863  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2020-05-02 00:05:27.863  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2020-05-02 00:05:27.864  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2020-05-02 00:05:27.864  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Application is null : false
2020-05-02 00:05:27.864  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2020-05-02 00:05:27.864  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2020-05-02 00:05:27.864  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2020-05-02 00:05:28.006  INFO 16528 --- [RMI TCP Connection(3)-127.0.0.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-05-02 00:05:28.007  INFO 16528 --- [RMI TCP Connection(3)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-05-02 00:05:28.018  INFO 16528 --- [RMI TCP Connection(3)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 10 ms
2020-05-02 00:05:28.022  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : The response status is 200
2020-05-02 00:05:28.026  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Starting heartbeat executor: renew interval is: 1
2020-05-02 00:05:28.029  INFO 16528 --- [restartedMain] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 4
2020-05-02 00:05:28.033  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1588358128032 with initial instances count: 1
2020-05-02 00:05:28.038  INFO 16528 --- [restartedMain] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application USER-SERVICE with eureka with status UP
2020-05-02 00:05:28.038  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1588358128038, current=UP, previous=STARTING]
2020-05-02 00:05:28.039  WARN 16528 --- [restartedMain] c.n.discovery.InstanceInfoReplicator     : Ignoring onDemand update due to rate limiter
2020-05-02 00:05:28.042  INFO 16528 --- [restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2020-05-02 00:05:28.046  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:05:28.071  INFO 16528 --- [restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2020-05-02 00:05:28.123  INFO 16528 --- [restartedMain] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2020-05-02 00:05:28.301  INFO 16528 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8100 (http) with context path ''
2020-05-02 00:05:28.303  INFO 16528 --- [restartedMain] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 8100
2020-05-02 00:05:28.704  INFO 16528 --- [restartedMain] c.m.user.app.UserServiceApplication      : Started UserServiceApplication in 10.033 seconds (JVM running for 11.195)
2020-05-02 00:05:29.052  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - Re-registering apps/USER-SERVICE
2020-05-02 00:05:29.054  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100: registering service...
2020-05-02 00:05:29.054  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:05:29.054  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:05:29.108  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - registration status: 204
2020-05-02 00:05:29.124  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:05:30.128  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:05:30.128  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:06:00.147  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:06:01.159  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:06:01.160  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:06:06.006  WARN 16528 --- [http-nio-8100-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.data.mapping.MappingException: No property user found on entity class com.microservices.user.app.entity.ShippingAddress to bind constructor parameter to!]
2020-05-02 00:06:31.186  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:06:32.207  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:06:32.208  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:06:43.789  INFO 16528 --- [Thread-10] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application USER-SERVICE with eureka with status DOWN
2020-05-02 00:06:43.790  WARN 16528 --- [Thread-10] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1588358203790, current=DOWN, previous=UP]
2020-05-02 00:06:43.799  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:06:43.799  INFO 16528 --- [Thread-10] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-05-02 00:06:43.816  INFO 16528 --- [Thread-10] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
2020-05-02 00:06:43.890  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - Re-registering apps/USER-SERVICE
2020-05-02 00:06:43.891  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100: registering service...
2020-05-02 00:06:43.898  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - registration status: 204
2020-05-02 00:06:44.807  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:06:44.808  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:06:44.829  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] o.s.c.h.RefreshScopeHealthIndicator      : Health check failed

org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'refreshScope': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:208) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1290) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:1925) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.cloud.health.RefreshScopeHealthIndicator.doHealthCheck(RefreshScopeHealthIndicator.java:49) ~[spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) ~[spring-boot-actuator-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_171]
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_171]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_171]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[na:1.8.0_171]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:195) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getHealthStatus(EurekaHealthCheckHandler.java:176) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.netflix.eureka.EurekaHealthCheckHandler.getStatus(EurekaHealthCheckHandler.java:170) ~[spring-cloud-netflix-eureka-client-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.netflix.discovery.DiscoveryClient.refreshInstanceInfo(DiscoveryClient.java:1419) ~[eureka-client-1.9.17.jar:1.9.17]
	at com.netflix.discovery.InstanceInfoReplicator.run(InstanceInfoReplicator.java:117) ~[eureka-client-1.9.17.jar:1.9.17]
	at com.netflix.discovery.InstanceInfoReplicator$1.run(InstanceInfoReplicator.java:101) ~[eureka-client-1.9.17.jar:1.9.17]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_171]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]

2020-05-02 00:06:44.838  INFO 16528 --- [Thread-10] com.netflix.discovery.DiscoveryClient    : Unregistering ...
2020-05-02 00:06:44.845  INFO 16528 --- [Thread-10] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - deregister  status: 200
2020-05-02 00:06:44.864  INFO 16528 --- [Thread-10] com.netflix.discovery.DiscoveryClient    : Completed shut down of DiscoveryClient
2020-05-02 00:06:46.118  INFO 16528 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:06:47.124  INFO 16528 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:06:47.125  WARN 16528 --- [restartedMain] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:06:47.128  INFO 16528 --- [restartedMain] c.m.user.app.UserServiceApplication      : No active profile set, falling back to default profiles: default
2020-05-02 00:06:47.981  INFO 16528 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2020-05-02 00:06:47.982  INFO 16528 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2020-05-02 00:06:47.996  INFO 16528 --- [restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 14ms. Found 1 Redis repository interfaces.
2020-05-02 00:06:48.098  INFO 16528 --- [restartedMain] o.s.cloud.context.scope.GenericScope     : BeanFactory id=62290dc6-6f8a-3087-8ea1-757c4ba46ebd
2020-05-02 00:06:48.358  INFO 16528 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8100 (http)
2020-05-02 00:06:48.359  INFO 16528 --- [restartedMain] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-05-02 00:06:48.361  INFO 16528 --- [restartedMain] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.33]
2020-05-02 00:06:48.395  INFO 16528 --- [restartedMain] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-05-02 00:06:48.395  INFO 16528 --- [restartedMain] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 1252 ms
2020-05-02 00:06:48.933  INFO 16528 --- [restartedMain] o.s.b.d.a.OptionalLiveReloadServer       : LiveReload server is running on port 35729
2020-05-02 00:06:49.086  INFO 16528 --- [restartedMain] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path '/actuator'
2020-05-02 00:06:49.127  INFO 16528 --- [restartedMain] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2020-05-02 00:06:49.134  WARN 16528 --- [restartedMain] c.n.c.sources.URLConfigurationSource     : No URLs will be polled as dynamic configuration sources.
2020-05-02 00:06:49.134  INFO 16528 --- [restartedMain] c.n.c.sources.URLConfigurationSource     : To enable URLs as dynamic configuration sources, define System property archaius.configurationSource.additionalUrls or make config.properties available on classpath.
2020-05-02 00:06:49.199  INFO 16528 --- [restartedMain] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-05-02 00:06:49.757  WARN 16528 --- [restartedMain] ockingLoadBalancerClientRibbonWarnLogger : You already have RibbonLoadBalancerClient on your classpath. It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead. In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or remove spring-cloud-starter-netflix-ribbon from your project.
2020-05-02 00:06:49.800  INFO 16528 --- [restartedMain] o.s.c.n.eureka.InstanceInfoFactory       : Setting initial instance status as: STARTING
2020-05-02 00:06:49.803  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Initializing Eureka in region us-east-1
2020-05-02 00:06:49.809  INFO 16528 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON encoding codec LegacyJacksonJson
2020-05-02 00:06:49.809  INFO 16528 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using JSON decoding codec LegacyJacksonJson
2020-05-02 00:06:49.810  INFO 16528 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML encoding codec XStreamXml
2020-05-02 00:06:49.810  INFO 16528 --- [restartedMain] c.n.d.provider.DiscoveryJerseyProvider   : Using XML decoding codec XStreamXml
2020-05-02 00:06:49.878  INFO 16528 --- [restartedMain] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-05-02 00:06:49.878  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2020-05-02 00:06:49.879  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2020-05-02 00:06:49.879  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2020-05-02 00:06:49.879  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Application is null : false
2020-05-02 00:06:49.879  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2020-05-02 00:06:49.879  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2020-05-02 00:06:49.879  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2020-05-02 00:06:49.883  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : The response status is 200
2020-05-02 00:06:49.884  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Starting heartbeat executor: renew interval is: 1
2020-05-02 00:06:49.884  INFO 16528 --- [restartedMain] c.n.discovery.InstanceInfoReplicator     : InstanceInfoReplicator onDemand update allowed rate per min is 4
2020-05-02 00:06:49.885  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Discovery Client initialized at timestamp 1588358209885 with initial instances count: 1
2020-05-02 00:06:49.885  INFO 16528 --- [restartedMain] o.s.c.n.e.s.EurekaServiceRegistry        : Registering application USER-SERVICE with eureka with status UP
2020-05-02 00:06:49.886  INFO 16528 --- [restartedMain] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1588358209886, current=UP, previous=STARTING]
2020-05-02 00:06:49.887  WARN 16528 --- [restartedMain] c.n.discovery.InstanceInfoReplicator     : Ignoring onDemand update due to rate limiter
2020-05-02 00:06:49.887  INFO 16528 --- [restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2020-05-02 00:06:49.888  INFO 16528 --- [restartedMain] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2020-05-02 00:06:49.888  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:06:49.896  INFO 16528 --- [restartedMain] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2020-05-02 00:06:49.937  INFO 16528 --- [restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8100 (http) with context path ''
2020-05-02 00:06:49.938  INFO 16528 --- [restartedMain] .s.c.n.e.s.EurekaAutoServiceRegistration : Updating port to 8100
2020-05-02 00:06:50.321  INFO 16528 --- [restartedMain] c.m.user.app.UserServiceApplication      : Started UserServiceApplication in 5.0 seconds (JVM running for 92.811)
2020-05-02 00:06:50.325  INFO 16528 --- [restartedMain] .ConditionEvaluationDeltaLoggingListener : Condition evaluation unchanged
2020-05-02 00:06:50.894  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - Re-registering apps/USER-SERVICE
2020-05-02 00:06:50.895  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100: registering service...
2020-05-02 00:06:50.895  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:06:50.895  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:06:50.907  INFO 16528 --- [DiscoveryClient-HeartbeatExecutor-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/WKWIN1695984.global.publicisgroupe.net:user-service:8100 - registration status: 204
2020-05-02 00:06:50.915  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:06:51.919  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:06:51.919  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:07:08.275  INFO 16528 --- [http-nio-8100-exec-2] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2020-05-02 00:07:08.276  INFO 16528 --- [http-nio-8100-exec-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2020-05-02 00:07:08.281  INFO 16528 --- [http-nio-8100-exec-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 4 ms
2020-05-02 00:07:21.936  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:07:22.954  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:07:22.954  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:07:52.975  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:07:53.996  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:07:53.996  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:08:24.015  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:08:25.026  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:08:25.027  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:08:55.046  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:08:56.063  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:08:56.064  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:09:26.085  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:09:27.101  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:09:27.102  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:09:57.121  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:09:58.139  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:09:58.140  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:10:28.164  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 00:10:29.172  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 00:10:29.174  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 00:10:59.203  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 03:10:59.652  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 03:10:59.652  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:34:32.947  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:34:33.953  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:34:33.953  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:34:51.921  INFO 16528 --- [AsyncResolver-bootstrap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-05-02 12:35:03.961  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:35:04.977  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:35:04.978  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:35:34.986  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:35:35.991  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:35:35.991  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:36:06.000  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:36:07.022  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:36:07.023  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:36:37.035  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:36:38.043  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:36:38.044  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:37:08.056  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:37:09.065  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:37:09.066  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:37:39.087  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:37:40.102  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:37:40.103  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:38:10.121  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:38:11.129  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:38:11.130  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:38:41.145  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:38:42.153  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:38:42.154  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:39:12.169  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:39:13.181  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:39:13.182  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:39:43.200  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:39:44.209  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:39:44.210  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:39:51.924  INFO 16528 --- [AsyncResolver-bootstrap-executor-0] c.n.d.s.r.aws.ConfigClusterResolver      : Resolving eureka endpoints via configuration
2020-05-02 12:40:14.221  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:40:15.230  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:40:15.230  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:40:45.251  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:40:46.265  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:40:46.266  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:41:16.293  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:41:17.309  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:41:17.310  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:41:47.339  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:41:48.351  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:41:48.352  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:42:18.378  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:42:19.392  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:42:19.393  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:42:49.423  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:42:50.437  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:42:50.437  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:55:08.707  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:55:09.713  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:55:09.713  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:55:39.723  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:55:40.727  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:55:40.727  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:56:10.737  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:56:11.743  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:9004. Will be trying the next url if available
2020-05-02 12:56:11.743  WARN 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:9004/user-service/default": Connection refused: connect; nested exception is java.net.ConnectException: Connection refused: connect
2020-05-02 12:56:37.769  INFO 16528 --- [Thread-18] o.s.c.n.e.s.EurekaServiceRegistry        : Unregistering application USER-SERVICE with eureka with status DOWN
2020-05-02 12:56:37.770  WARN 16528 --- [Thread-18] com.netflix.discovery.DiscoveryClient    : Saw local status change event StatusChangeEvent [timestamp=1588404397770, current=DOWN, previous=UP]
2020-05-02 12:56:37.800  INFO 16528 --- [Thread-18] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2020-05-02 12:56:37.801  INFO 16528 --- [DiscoveryClient-InstanceInfoReplicator-0] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:9004
2020-05-02 12:56:37.807  INFO 16528 --- [Thread-18] com.netflix.discovery.DiscoveryClient    : Shutting down DiscoveryClient ...
